name: publish
on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  quality-gates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm install
      - name: prettier
        run: npm run prettier:check
  publish:
    if: github.ref_name == 'master'
    needs: quality-gates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: git config
        run: |
          git config --global user.email "njkznu@gmail.com"
          git config --global user.name "kuzanatoliy"
      - name: minor tag
        if: github.event_name == 'push'
        run: npm version minor
      - name: major tag
        if: github.event_name == 'workflow_dispatch'
        run: npm version major
      - name: push commits
        run: |
          git push
          git push --tags
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
