name: publish
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - name: git config
        run: |
          git config --global user.email "njkznu@gmail.com"
          git config --global user.name "kuzanatoliy"
      - name: minor tag
        if: github.event_name == 'push'
        run: npm version minor
      - name: major tag
        if: github.event_name == 'workflow_dispatch'
        run: npm version minor
      - name: push commits
        run: |
          git push
          git push --tags
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
